### ISSUE TITLE
Use nested set attributes to check if comment has children

### ISSUE THREAD

**Issue by szwagros** [Slynova-Org/laravel-commentable-example#2]
Hi,

when checking if comment has children would it not be better if instead of querying relation:

```
    public function hasChildren()
    {
        return $this->children()->count() > 0;
    }
```

use the fact that it is nested set and replace it with :

```
    public function hasChildren()
    {
        return (($this->rgt - $this->lft - 1) / 2) > 0;
    }
```

Especially when you have a lot of comments to display but only few are nested. Then there is a lot of queries that return 0.

**Comment by RomainLanz** [comment]
Can you make a PR ?
